### ISSUE TITLE
Doesn't launch the intent... error: %result_code

### ISSUE THREAD

**Issue by AlishaPink** [agnostic-apollo/TaskerLauncherShortcut-Tasker-Project#1]
Helloooo, Even 2 years on, this is pretty much the only way to launch DEEP_SHORTCUT intents from tasker. I thank you for your efforts @agnostic-apollo

But unfortunately it is not working on my device! Despite setting the default launcher variable, and correct intent... it simply does not launch the intent. Only this "%result_code" is flashed on screen. I have root and tasker is granted root permissions as well.

The "Get And Set Default Launcher" task runs just fine. But the intent never launches.

I'm on Android 8.0
Nova Launcher

This is the intent, incase it helps...
`#Intent;action=android.intent.action.MAIN;category=com.android.launcher3.DEEP_SHORTCUT;launchFlags=0x10200000;package=com.excelliance.multiaccounts;component=com.excelliance.multiaccounts/com.pi1d.l6v.ahi33xca.dhy60gm84keol;i.profile=0;S.shortcut_id=whatsappnew;end`

I would *really* appreciate if you could give me some advice and help me fix it. I've been trying to get this to work for AGES.

**Comment by agnostic-apollo** [comment]
You are very welcome.

Is the issue with that specific intent, or all intents?

You haven't provided details of how you are running the intent, which task are you using to launch it and the parameters passed? Post task description after exporting it. I assume, you have have already installed the [TaskerLauncherShortcut](https://github.com/agnostic-apollo/TaskerLauncherShortcut) app since likely that's where you got the intent.

>com.pi1d.l6v.ahi33xca.dhy60gm84keol;

That's an obfuscated class name, the shortcut would likely break on updates if new random name is generated at build time. Should be reported to the dev.

**Comment by AlishaPink** [comment]
Thank you for replying so swifty! 

The issue is with all intents... for example, I tried a regular chrome "add to home" shortcut of yahoo.com.
`#Intent;action=android.intent.action.MAIN;category=com.android.launcher3.DEEP_SHORTCUT;launchFlags=0x10200000;package=com.android.chrome;component=com.android.chrome/com.google.android.apps.chrome.Main;i.profile=0;S.shortcut_id=3fabfd57-c435-4533-bf45-38265a43977c;end`

I even installed kiwi browser to test your template, but it still doesn't work.

As to how i'm running the intent, i literally just imported your project. And i'm running your templates directly. - https://github.com/agnostic-apollo/TaskerLauncherShortcut-Tasker-Project/releases

Since i'm using nova launcher as well, I've changed only 1 thing (as per your instructions) - the intent uri in "TaskerLauncherShortcut DEEP_SHORTCUT Template" from the default kiwi browser incognito tab to my own intent uri. And yes, I do have the TaskerLauncherShortcut app.

Yes, you're right, the class name in the intent might be randomly generated but i rarely (if ever) update that app so it shouldn't be an issue. I'm just desperate for this to work once!! haha 

PS. if you still want me to export and upload the task description, let me know 💕

**Comment by agnostic-apollo** [comment]
hmm, could be that plugin action is failing. Change your default launcher to `TaskerLauncherShortcut` app manually, then create a new task in tasker with the `TaskerLauncherShortcut` plugin action and add uri in the plugin config and make sure `Continue Task After Error` toggle is disabled. Also add another flash action for `%result_code %errmsg` and then run the task.

**Comment by AlishaPink** [comment]
I really can't thank you enough for still being engaged with my queries despite the project developed years ago! 

You know, till this day, there are threads and posts on reddit, stackoverflow, etc forums about this but nobody has stepped up to try solve this shortcuts issue.

So I tried out exactly what you said but still no luck. The tasks run fine but the intent doesn't launch and the flash action just gives `%result_code %errmsg` 😩

I'm on Tasker version 5.11.1, if that matters at all.

**Comment by agnostic-apollo** [comment]
Hey, no worries, support is part of the job. :)

Weird that you are having issues, haven't received them before.

Does plugin action have green or red dot when you run the task. Maybe flash `%err` has well.

Which phone and rom are you using, maybe its related to `Auto Start` or `Auto Launch` preventing plugin to receive the command from tasker. Check https://dontkillmyapp.com for device specific optimizations and disable them for `TaskerLauncherShortcut` app.

You should be able to diagnose rom issues with `logcat`. Run plugin task, then quickly run `adb logcat -d > logcat.txt` on pc, and look for errors related to `com.agnostic.apollo.taskerlaunchershortcut` or `FireReceiver`.

https://developer.android.com/studio/command-line/logcat

Project was exported on an even older version, so should work.

https://github.com/agnostic-apollo/TaskerLauncherShortcut-Tasker-Project/blob/341a9dfc8925467e551750a6be03c51232affb30/projects/TaskerLauncherShortcut.prj.md?plain=1#L4

**Comment by AlishaPink** [comment]
I'm scratching my head too! The tasks excecute just fine, (green dot on the plugin action), even the `Get and Set Default Launcher` task works perfectly. It's just no intent actually launches.

I've allowed everything for Tasker, TaskerLauncherShortcut app, even the apps which we're trying to launch - `Auto Start`, `Start in Background`, `No battery optimizatations`

I ran adb logcat and the only things i could see which *might* have something to do with the issue is this, there's no errors or anything else in the log - 

```
ActivityManager: Permission Denial: Accessing service ComponentInfo{com.android.vending/com.google.android.finsky.services.LicensingService} from pid=14775, uid=10519 requires com.android.vending.CHECK_LICENSE

PackageManager: Replacing preferred activity com.agnostic.apollo.taskerlaunchershortcut/.LauncherHomeActivity for user 0:
```

After setting the default launcher to `TaskerLauncherShortcut`, is there any way we can run the intent *without* tasker? Maybe from ADB, shell, script? That would help us figure out if tasker is the issue or rom, perms, etc

**Comment by agnostic-apollo** [comment]
Those `logcat` entries are unrelated.

Do you see any entries with the tag `custom_taskerlaunchershortcut_log` (this may have been trimmed).

There should be one for `"Shortcut Intent Received By FireReceiver`. If that doesn't exist, then it means that `TaskerLauncherApp` is not receiving the intent at all. Would be easier if  you sent the `logcat` dump near the time of the intent after removing any private info. Can email me at agnosticapollo@gmail.com too.

https://github.com/agnostic-apollo/TaskerLauncherShortcut/blob/25e21df3eef56de084ca941338c5754db30f20b2/app/src/main/java/com/agnostic/apollo/taskerlaunchershortcut/receiver/FireReceiver.java#L59

 >is there any way we can run the intent without tasker? Maybe from ADB, shell, script? 

`am` command doesn't support sending a bundle object so `FireReceiver` can't be triggered directly. But launcher activity can with `adb shell "am start-activity -n 'com.agnostic.apollo.taskerlaunchershortcut/.LauncherHomeActivity' -a action_fire_shortcut_intent_uri --es arg_shortcut_intent_uri '#Intent;action=android.intent.action.MAIN;category=com.android.launcher3.DEEP_SHORTCUT;launchFlags=0x10200000;package=com.android.chrome;component=com.android.chrome/com.google.android.apps.chrome.Main;i.profile=0;S.shortcut_id=dynamic-new-incognito-tab-shortcut;end'"`

**Comment by AlishaPink** [comment]
I checked the logcat pretty thoroughly, but i can't find anything mentioning `taskerlaunchershortcut` or  `FireReceiver` as you said. 

Here is the attached logcat dump before and after setting `TaskerLauncherShortcut` app as default launcher and running the default DEEP_SHORTCUT task in tasker.  - [adb logcat.txt](https://github.com/agnostic-apollo/TaskerLauncherShortcut-Tasker-Project/files/9568310/adb.logcat.txt)

Maybe you can spot something i'm missing. *fingers crossed*

Also, the shell command you provided WORKS!! It's fantastic. I was actually able to replicate a similar workflow as your template in tasker. Making `TaskerLauncherShortcut` the default launcher via shell, then execute the `am start...` command, waiting for a few seconds, and then finally setting back to my default launcher via shell. 

It works great, it is alittle dirty because it flashes your launcher for a few seconds before opening the intent. But i was just happy to see the intent actually launching haha. 

Hopefully we can get to the bottom of this. 💕

**Comment by agnostic-apollo** [comment]
Well, its great to hear that plugin works for launching shortcut at least.

If `FireReceiver` way starts working, then it won't flash launcher. It only needs to be done on Android 10+ due to android restrictions.

> but i can't find anything mentioning taskerlaunchershortcut

There are 41 entries related to that. How did you miss? Which app are you using? I suggest using SublimeText on pc or QuickEdit on android, or some other good editor that can open large files.

I don't see anything related to `FireReceiver`, so its likely not getting triggered. But you have trimmed the logcat so may have removed important entries.

It could be a Tasker issue, have you considered updating? ;)

Joao posts all versions at https://drive.google.com/drive/folders/1GW55YKFiuOZhJVswnt_BQUCJoGm36ugF so you don't need to update to latest.

To check if a tasker issue, import the following task and change `%shortcut_intent_uri` and set default launcher to `TaskerLauncherShortcut` and run the task. If it works, then issue with tasker plugin action. If it does not, then need `logcat` output. Are other plugins working for you?

[TaskerLauncherShortcut_Java.zip](https://github.com/agnostic-apollo/TaskerLauncherShortcut-Tasker-Project/files/9568546/TaskerLauncherShortcut_Java.zip)

**Comment by AlishaPink** [comment]
Good News!! (and a small apology) 😅

So long story short, it was the tasker version which isn't happy with the `TaskerLauncherShortcut`... for reasons which are beyond me haha.

I updated from 5.11.1 beta to 5.13.7 and bingo it works. What is curious that all other plugins and functions, tasks, etc were working on 5.11.1 as well. But it had a problem with `TaskerLauncherShortcut` in particular it seems. I downgraded back to 5.11.1 to double-check and yeah, doesn't work. Upgraded to 5.13.7+ and works flawlessly.

The apology, because I feel like i've wasted your time for such an inconsequential issue; as simple as updating tasker, which I should have done way earlier. All other task and plugins worked so i figured tasker is not the issue.

PS. I can be klutzy sometimes. 🙈 I meant I can't find anything *significant* mentioning taskerlaunchershortcut. I did see all the other entries. SublimeText on PC and TextWranger on Mac have always been favorites. 💕

**Comment by agnostic-apollo** [comment]
>and a small apology) sweat_smile

Yeah, that won't do! I shall be suing you for millions of dollars for time and emotional damages.

> I downgraded back to 5.11.1 to double-check and yeah, doesn't work. Upgraded to 5.13.7+ and works flawlessly.

Will have to take time to check tasker logs to see what happens, but not really worth it. I did check reddit post for around the release, there were some plugin issues but nothing that seemed exact.

https://www.reddit.com/r/tasker/comments/jemaxl/dev_tasker_5113beta_call_screening_and_a_bunch_of/

>PS. I can be klutzy sometimes. I meant I can't find anything significant mentioning taskerlaunchershortcut. I did see all the other entries.

Lolz, its fine. I uh, believe you! ;)

You were able to debug yourself and follow instructions, so that's a support experience I usually wish for! So all good!

> SublimeText on PC

Oh, wow! That's cool!

Closing since not a plugin issue and is resolved.

**Comment by AlishaPink** [comment]
Not millions please 😭 You can sue me for 10's of dollars, no worries 😝

Yeah! I guess if anyone else ever has an issue they should just try updating tasker to a version up -or- down... 🤔 

Thank you so much again. If only all Devs were as reachable and helpful as you are, it would make the world a better place 💕

**Comment by agnostic-apollo** [comment]
It is too much to ask to have at least some millionaire or billionaire user I could sue!

lolz, like I am gonna waste time suing and in courts just for 10's of dollars. I guess you are free! Enjoy! :D

>Yeah! I guess if anyone else ever has an issue they should just try updating tasker to a version up -or- down... thinking

You should join tasker beta development on r/tasker, its a running cycle of broken and fixed things :p

You are very welcome! That's nice of you to say! Thanks! :)
